### ISSUE TITLE
Port to MiSTer

### ISSUE THREAD

**Issue by retrocaster** [d18c7db/Gauntlet_FPGA#1]
Feature request:  Port this to MiSTer / de10-nano
There's a large userbase that would be eager to get this core, and you might get other developer contributions as well if you're looking for collaboration

More info here:
https://github.com/MiSTer-devel/Main_MiSTer/wiki
https://github.com/MiSTer-devel/Main_MiSTer/wiki/Core-porting-notes

There's an official forum on Atari-Forum, but it's currently undergoing maintenance:
http://www.atari-forum.com/viewforum.php?f=117

**Comment by d18c7db** [comment]
I don’t own a DE10 unfortunately. Weren’t some of the MiSTer guys already working on a port?

Cheers
Alex

**Comment by limi** [comment]
If we sent you a DE-10, would you accept it? The community is usually happy to donate hardware to any FPGA developers. 😊

**Comment by d18c7db** [comment]
Yes of course. I only have a Xilinx dev board so far which is why all my code is tested to run on Xilinx.

About a month ago Alan (alanswx) also mentioned the possibility of me getting a DE-10 from a European distributor but he got busy with other things and nothing ensued and I didn't follow that up either.

Cheers

Alex



________________________________

**Comment by cacophony1** [comment]
@d18c7db I sent you an email to the address listed on your github page, so you might want to check your spam folder if you don't see it. It sounds like there are multiple folks who would like to donate hardware to you.

**Comment by limi** [comment]
Let me know, @d18c7db — I’ll happily figure out how to send you a DE-10 nano from the US, but if you already have other offers, those might be the better option with the current shipping problems.

**Comment by d18c7db** [comment]
We are discussing this now in #fpga-elite, Matt Hargett, Alan S and Porkchop Express are offering

A

________________________________

**Comment by limi** [comment]
Great! Happy to cover any remaining costs.

**Comment by d18c7db** [comment]
MiSTer core released
