### ISSUE TITLE
Releases Folder

### ISSUE THREAD

**Issue by RetroDriven** [d18c7db/Gauntlet_FPGA#10]
Would it be possible to have the RBF and MRA files within a **releases**  folder? It would be handy for the Update Script that I made for Unofficial Cores.

**Comment by dfilskov** [comment]
Wouldn't it be easier if Alex simply added it to the official MiSTer repo?

**Comment by RetroDriven** [comment]
Yes that would be the best option if possible as well.

**Comment by d18c7db** [comment]
Can we chat this out on Discord?

**Comment by d18c7db** [comment]
Releases folder created
