### ISSUE TITLE
Support for Gauntlet II on Mister

### ISSUE THREAD

**Issue by Obiwantje** [d18c7db/Gauntlet_FPGA#13]
Is there any work in progress to attempt to also have Gauntlet II run on the Mister platform? (Pretty please)

**Comment by dpowers86** [comment]
If nobody is working on it, I'd certainly be up for the challenge. No promises though.

**Comment by d18c7db** [comment]
Yes there is work in progress on the SDRAM. For Gauntlet II and Vindicators part II to run on MiSTer the ROMs must be running out of SDRAM (there isn't enough internal FPGA memory to hold them). Anyone wishing to contribute is welcome. If you get it working before me you have my thanks :)

**Comment by d18c7db** [comment]
Done. Further work is in progress but for now it seems playable,

**Comment by dfilskov** [comment]
Yeehaa! - thank you :)
