### ISSUE TITLE
Support for MAME mappings for player 3 & 4

### ISSUE THREAD

**Issue by manast** [d18c7db/Gauntlet_FPGA#18]
Thanks for this great core! a lot of my child memories are revived with it. :).

I wonder if it would feasible to also add the MAME mappings for player 3 and 4 according to this documentation?
https://docs.mamedev.org/usingmame/defaultkeys.html#player-3-controls

Or is there any other workaround for us using IPAC-4 controllers? (it is just a keyboard controller with default mappings to MAME).

**Comment by d18c7db** [comment]
Thanks for the feedback. I've added P3 and P4 keyboard controls as requested, please test.

**Comment by dfilskov** [comment]
Will the new rbf become available here?

https://github.com/d18c7db/Gauntlet_FPGA/tree/master/MiSTer/Releases

**Comment by manast** [comment]
The rbf is actually here: https://github.com/d18c7db/Gauntlet_FPGA/tree/master/MiSTer/releases

**Comment by manast** [comment]
I am testing this. I will come back with the results.

**Comment by d18c7db** [comment]
There is some githubfuckery with case sensitivity so "Releases" and "releases" are different folders. Will try to fix it soon.

**Comment by manast** [comment]
ok, so player 4 works with default keys, but for player 3, magic button is currently mapped to Right Alt Graph, but it should be mapped to Right Shift.

**Comment by manast** [comment]
oh, btw something I noticed, when inserting coins for player 3 and 4, there is almost not sound, do not know if the original arcade was like this too though.

**Comment by d18c7db** [comment]
Ah sorry about that, I fumbled the key code for player 3, it's fixed now, just download the latest .rbf release. As for the coin sound for p3 p4 that is entirely under software control (ROMs) assuming you have the correct versions. The hardware (FPGA) implementation is clearly able to play the sounds as you saw for p1 p2.
