### ISSUE TITLE
MiSTer - Magic/Start is missing when assigning joystick buttons

### ISSUE THREAD

**Issue by dfilskov** [d18c7db/Gauntlet_FPGA#3]
When assigning buttons you can map Fire, Start player 1, Start player 2 and Coin.

But I believe the correct list would be Fire, Magic/Start and Coin ... since MiSTer automatically assigns joysticks to player 1, 2, 3 and 4 - each with their respective Magic/Start buttons in this case.

Perhaps the update can be taken from this repo (though for some reason the coin slot keyboard keys are moved from 1-4 to 5-8): https://github.com/funkycochise/Gauntlet_FPGA/commit/666b2d79e95ca0a851281d5cf73375297a48d52f

You could consider merging the cores and add it to the official MiSTer repo: https://github.com/MiSTer-devel

**Comment by d18c7db** [comment]
Yep that’s the plan.

**Comment by d18c7db** [comment]
OK merged in contribution by @funkycochise with support for up to four joysticks and he also changed the keyboard key assignments to be more in line with MAME. On my swedish keyboard the scan codes for arrow keys and ctrl/alt don't seem to match those from contributed code, but whatever, will sort it out later.

**Comment by dfilskov** [comment]
Good work! :) - thanks - looking forward to the next rbf !
