### ISSUE TITLE
Alternative Gauntlet ROM issue

### ISSUE THREAD

**Issue by rhester72** [d18c7db/Gauntlet_FPGA#5]
If launching the MRA for "Gauntlet (2 Players, rev 6), you get screen corruption followed by "ROM at 38000 error U L 5892"

EDIT: After a bit more testing, this seems to affect all of the 2-player versions (only)

**Comment by d18c7db** [comment]
Yeah we know. The 2P games need a different version slapstic which cannot be dynamically changed yet. The current rbf only supports 4P games. It’s on the to do list

**Comment by d18c7db** [comment]
Updated core with dynamic slapsic config through mra files, can now play all 4P and 2P ROMs.

**Comment by rhester72** [comment]
Confirmed - thank you!
