### ISSUE TITLE
MiSTer core sound volume is very low

### ISSUE THREAD

**Issue by dfilskov** [d18c7db/Gauntlet_FPGA#7]
At highest volume setting on MiSTer the sound volume is much lower than other cores.

To match other cores the **audio output amplitude should be doubled** a least once - perhaps even twice (or 1,5 times) - that's 6 dB, 12 dB or 9 dB.

**Comment by d18c7db** [comment]
+6dB increase

**Comment by dfilskov** [comment]
Tack så mycket :)
